apiVersion: apps/v1
kind: Deployment
metadata:
  name: telehealth-api-deployment
  namespace: telehealth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telehealth-api-deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: telehealth-api-deployment
    spec:
      containers:
        - name: telehealth-api-deployment
          image: ${DOCKERHUB_USERNAME}/telehealth-api:${IMAGE_TAG}
          imagePullPolicy: Always
          env:
            - name: POSTGRES_HOST
              value: "telehealth-api-db-service"
            - name: POSTGRES_USER 
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_PORT
              value: "5432"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
