apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
  namespace: telehealth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: demo-api
    # spec:
      # initContainers:
      #   - name: init-seed-images
      #     image: ${DOCKERHUB_USERNAME}/telehealth-images:50
      #     command:
      #       [
      #         "sh",
      #         "-c",
      #         'if [ -z "$(ls -A /app/images)" ]; then cp -r /seededImages/* /app/images/; fi',
      #       ]
      #     volumeMounts:
      #       - name: image-storage
      #         mountPath: /app/images
      # containers:
      #   - name: demo-api
      #     image: ${DOCKERHUB_USERNAME}/telehealth-api:${IMAGE_TAG}
      #     ports:
      #       - containerPort: 8080
      #     volumeMounts:
      #       - mountPath: /app/images
      #         name: image-storage

      # volumes: 
      #   - name: image-storage
      #     persistentVolumeClaim:
      #       claimName: demo-api-pvc
        



        
        # readinessProbe:
        #   httpGet:
        #     path: /api/health
        #     port: 8080
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        #   timeoutSeconds: 3
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 15
        #   periodSeconds: 20