apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: telehealth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: ${DOCKERHUB_USERNAME}/telehealth-api:${IMAGE_TAG}
          imagePullPolicy: Always
          env:
            - name: POSTGRES_HOST
              value: "telehealth-api-db-service"
            - name: POSTGRES_USER 
              value: "${PG_USER}"
            - name: POSTGRES_PASSWORD
              value: "${PG_PASSWORD}"
            - name: POSTGRES_DB
              value: "${PG_DB}"
            - name: POSTGRES_PORT
              value: "5432"
          # ports:
          #   - containerPort: 8080
          # readinessProbe:
          #   httpGet:
          #     path: /api/health
          #     port: 8080
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          #   timeoutSeconds: 3
          # livenessProbe:
          #   httpGet:
          #     path: /api/health
          #     port: 8080
          #   initialDelaySeconds: 15
          #   periodSeconds: 20