apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mustafa
  name: demo-api-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client