apiVersion: v1
kind: Service
metadata:
  name: telehealth-api-service
  namespace: telehealth-api
spec:
  selector:
    app: telehealth-api-deployment
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
