# CI
name: Deployment to alex server 4
on:
  push:
    branches:
    - main
jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/telehealth-client:${{ github.run_number}} .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/telehealth-client:${{ github.run_number}}
# CD
    - name: Deploy to Kubernetes
      run: |
        export PATH=$PATH:~/.nix-profile/bin:/nix/var/nix/profiles/default/bin
        export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
        export IMAGE_TAG=${{ github.run_number }}
        kubectl -n mustafa delete configmap telehealth-web-postgres-init || true 
        ls
        kubectl -n mustafa create configmap telehealth-web-postgres-init --from-file=schema.sql
        for file in kube/*; do 
            cat "$file" | envsubst | kubectl apply -f -; 
        done
