name: Deployment api & db to alex server 4
on:
  push:
    branches:
    - main
  # workflow_dispatch: 

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/telehealth_api:latest -t ${{ secrets.DOCKERHUB_USERNAME }}/telehealth_api:${{ github.run_number }} .
        docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/telehealth_api
  

    - name: Deploy to Kubernetes
      run: |
        export PATH=$PATH:~/.nix-profile/bin:/nix/var/nix/profiles/default/bin
        export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
        export IMAGE_TAG=${{ github.run_number }}
        export PG_USER=${{ secrets.PG_USER }}
        export PG_DB=${{ secrets.PG_DB }}
        export PG_PASSWORD=${{ secrets.PG_PASSWORD }}

        for file in kube/*; do
            cat "$file" | envsubst | kubectl apply -f -;
        done
