name: Deployment api to alex server 2
on:
  push:
    branches:
    - main
  # workflow_dispatch:

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push API
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/telehealth-api:${{ github.run_number }} -t ${{ secrets.DOCKERHUB_USERNAME }}/telehealth-api:latest .
        docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/telehealth-api

    # - name: Build and push SeededImages 
    #   run: |
    #     docker build -f Dockerfile.images -t ${{ secrets.DOCKERHUB_USERNAME }}/telehealth-images:${{ github.run_number }} -t ${{ secrets.DOCKERHUB_USERNAME }}/telehealth-api:latest .
    #     docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/telehealth-images

    - name: Deploy to Kubernetes
      run: |
        export PATH=$PATH:~/.nix-profile/bin:/nix/var/nix/profiles/default/bin
        export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
        export IMAGE_TAG=${{ github.run_number }}

        for file in kube/*; do
            cat "$file" | envsubst | kubectl apply -f -;
        done
